### ISSUE TITLE
start_on to end_on per user

### ISSUE THREAD

**Issue by wintermeyer** [3Stones-io/omedis#113]
Currently the `tenant` resource has these attributes for the start and the end of the working day:

```elixir
:daily_start_at,
:daily_end_at,
```

But we actually want to have that information on a `user` level.

## Tasks

- [ ] rename `daily_start_at` to `default_daily_start_at` (same with daily_end_at)
- [ ] add `daily_start_at` and `daily_end_at` attributes to the `user` resource
- [ ] use the `tenant` defaults of those values for the `user#new` form. So it can be changed but there is a good default.
- [ ] rewire the `today` LiveView to use the `user` attributes

## Misc

As always: 
- Please feel free to split up this issue into sub issues.
- Please ask questions or discuss within the issue so that everybody involves knows what is going on.

This is what we are talking about:

<img width="547" alt="Bildschirmfoto 2024-10-01 um 09 07 29" src="https://github.com/user-attachments/assets/6c29dce3-1fcc-4d54-a53d-019ddc932e57">
