### ISSUE TITLE
Add language flags for the register when current_user == nil

### ISSUE THREAD

**Issue by wintermeyer** [3Stones-io/omedis#121]
We are talking about http://localhost:4000/register

<img width="1499" alt="Bildschirmfoto 2024-10-01 um 11 40 17" src="https://github.com/user-attachments/assets/0a1dc192-a303-4016-868b-e5562697e598">

Problem: Display the form in a language that can be understood by the user. Because the `current_user` is `nil` we don't know the correct language.

## Tasks

- [ ] Use the browsers language as a default to display the language on this page.
- [ ] Display the flags (use Emojis) of the available languages where the arrow is.
- [ ] Add a functionality that by clicking on one of the flags the form is displayed in that language.
- [ ] Check if the design works on mobile and desktop. Change if needed.
