### ISSUE TITLE
Improve /tenants/:tenant_slug/groups/:group_slug/log_categories

### ISSUE THREAD

**Issue by wintermeyer** [3Stones-io/omedis#128]
What we are talking about:

<img width="1688" alt="Bildschirmfoto 2024-10-02 um 08 49 43" src="https://github.com/user-attachments/assets/d664e920-8bfc-4b3d-aa46-df11eece7f15">

This can be improved to be easier to use for humans.

## Tasks

- [x] Add a `slug` attribute to the `LogCategory` resource. Have a look at the `Tenant` resource how slugs can be created automatically.
#130 
- [x] Remove the `ID` field from #index and #show
#131
- [x] Replace the `group_id` with `group_slug` and link it to that group (<a href ...)
#133
- [x] Display the `name` of the `LogCategory` as a button which shows the `color_code` color.
#134
- [x] Implement a user friendly way to change the `position` of a `LogCategory` by adding an up and down arrow in the index view. Right now changing the position is a night mare. Use the "Ash way" to solve this problem. We should be able to do this task in the iex too.
#139
