### ISSUE TITLE
Create TimeTracking for today

### ISSUE THREAD

**Issue by wintermeyer** [3Stones-io/omedis#14]
Implement the code @MICHAELMUNAVU83 already wrote:

<img width="427" alt="Bildschirmfoto 2024-09-16 um 07 44 23" src="https://github.com/user-attachments/assets/750fddc7-9ac7-4def-9fa9-3a562fe577be">

Make it available for logged in users at `/today` and add a link to it at the `index` page.

Create other issues when needed. Use common sense (e.g. add needed validations and write tests).

## Tasks

- [ ] Create a `LogCategory` resource with a web GUI CRUD. 
       Attributes: 
       - `name`
       - `tenant_id` (belongs_to)
       -  The usual timestamps.
- [ ] Create a LiveView system for that page which updates the red line for the current time every minute. Display and update the time in `24:00` format somewhere in the navigation part too.
- [ ] Create a `LogEntry` resource with a web GUI CRUD. 
       Attributes: 
       - `user_id` (belongs_to)
       - `start_at` (time)
       - `end_at` (time)
       - `category_id` (belongs_to)
       - `comment` (text).
- [ ] When a user clicks on a LogCategory button. A new `LogEntry` should be created with the current time as the value for `start_at`. The next time a LogCategory button is clicked that old LogEntry should be updated with current time as the value for `end_at`
- [ ] Display the LogEntries for today and that user.
