### ISSUE TITLE
Add slug to Tenant

### ISSUE THREAD

**Issue by wintermeyer** [3Stones-io/omedis#35]
/tenants/:tenant_slug
/tenants/:tenant_slug/log_categories

# Tasks

- [ ] Add a `slug` attribute to the `Tenant` resource.
- [ ] Add the slug to the forms for create and update.
- [ ] Add a unique validation for the slug.
- [ ] Add a maximum length of 80 characters.
- [ ] Use something like https://github.com/jayjun/slugify to pre fill the slug.
- [ ] Chance all the internal links so that they use the `slug` and not the `id`.
- [ ] Remove the `id` from `index` and `show`. Add the `slug`.
