### ISSUE TITLE
Basic Chat Application

### ISSUE THREAD

**Issue by wintermeyer** [3Stones-io/omedis#464]
The chat is designed to facilitate seamless communication between users in real-time. It provides the ability to create and manage chatrooms, exchange messages, and track message interactions. The system ensures scalability, data integrity, and extensibility to meet diverse user requirements.

## Key Features:
1. **User Management**:
   - Users are managed via the existing `Omedis.Accounts.User` resource.
   - Users can join multiple chatrooms and participate in discussions.

2. **Chatroom Management**:
   - Users can create and join chatrooms.
   - Each chatroom has a unique name and tracks membership information.

3. **Messaging**:
   - Messages can be sent within chatrooms, supporting features like replies and priority tagging.
   - Soft-deletion of messages ensures auditability without permanent removal.

4. **Read Tracking**:
   - Tracks which users have viewed specific messages and when.
   - Provides granular insights into message interactions.

PS: Group chats will be implemented later on (which is pretty simple since the data model already covers it).

## Data Model

Here is a diagram of the resources we need for a basic chat application within Omedis

```mermaid
erDiagram
    User {
        int id
        string email
    }
    Chatroom {
        int id
        string name
        datetime created_at
        datetime updated_at
    }
    ChatroomMembers {
        int user_id
        int chatroom_id
        datetime inserted_at
        datetime updated_at
    }
    ChatMessage {
        int id
        int user_id
        int chatroom_id
        text message
        int reply_to_message_id
        boolean is_priority
        datetime inserted_at
        datetime updated_at
        datetime deleted_at
    }
    ChatMessageView {
        int id
        int user_id
        int chat_message_id
        datetime viewed_at
    }
    User ||--o{ ChatroomMembers : "joins"
    Chatroom ||--o{ ChatroomMembers : "has members"
    Chatroom ||--o{ ChatMessage : "contains"
    User ||--o{ ChatMessage : "sends"
    ChatMessage ||--o{ ChatMessageView : "viewed by"
    User ||--o{ ChatMessageView : "views"
```

## Ash Resources

Here is the pseudo code for the Ash resources:

```elixir
defmodule Omedis.Chat.Chatroom do
  use Ash.Resource,
    data_layer: AshPostgres.DataLayer

  postgres do
    table "chatrooms"
    repo Omedis.Repo
  end

  actions do
    defaults [:create, :read, :update, :destroy]
  end

  attributes do
    attribute :name, :string do
      allow_nil? false
    end

    create_timestamp :inserted_at
    update_timestamp :updated_at
  end

  relationships do
    has_many :chat_messages, Omedis.Chat.ChatMessage, destination_field: :chatroom_id
    has_many :chatroom_members, Omedis.Chat.ChatroomMember, destination_field: :chatroom_id
  end
end


defmodule Omedis.Chat.ChatroomMember do
  use Ash.Resource,
    data_layer: AshPostgres.DataLayer

  postgres do
    table "chatroom_members"
    repo Omedis.Repo
  end

  actions do
    defaults [:create, :read, :update, :destroy]
  end

  attributes do
    create_timestamp :inserted_at
    update_timestamp :updated_at
  end

  relationships do
    belongs_to :user, Omedis.Accounts.User, primary_key?: true
    belongs_to :chatroom, Omedis.Chat.Chatroom, primary_key?: true
  end
end


defmodule Omedis.Chat.ChatMessage do
  use Ash.Resource,
    data_layer: AshPostgres.DataLayer

  postgres do
    table "chat_messages"
    repo Omedis.Repo
  end

  actions do
    defaults [:create, :read, :update]

    destroy :soft_delete do
      argument :destroyed_at, :utc_datetime_usec, default: &DateTime.utc_now/0
      change set_attribute(:deleted_at, arg(:destroyed_at))
    end
  end

  attributes do
    attribute :message, :string do
      allow_nil? false
    end

    attribute :reply_to_message_id, :uuid do
      allow_nil? true
    end

    attribute :is_priority, :boolean do
      default false
    end

    create_timestamp :inserted_at
    update_timestamp :updated_at

    attribute :deleted_at, :utc_datetime_usec do
      allow_nil? true
    end
  end

  relationships do
    belongs_to :user, Omedis.Accounts.User
    belongs_to :chatroom, Omedis.Chat.Chatroom

    has_many :chat_message_views, Omedis.Chat.ChatMessageView, destination_field: :chat_message_id
  end
end


defmodule Omedis.Chat.ChatMessageView do
  use Ash.Resource,
    data_layer: AshPostgres.DataLayer

  postgres do
    table "chat_message_views"
    repo Omedis.Repo
  end

  actions do
    defaults [:create, :read]
  end

  attributes do
    create_timestamp :viewed_at
  end

  relationships do
    belongs_to :user, Omedis.Accounts.User do
      allow_nil? false
    end

    belongs_to :chat_message, Omedis.Chat.ChatMessage do
      allow_nil? false
    end
  end
end
```

## Tasks

- [ ] #500
- [ ]  Add validations which make sense
- [ ]  Add policies which make sense
- [ ]  Add documentation how to use the chat application from `iex` (e.g. send a message to an other user)
- [ ]  Add or change stuff that @wintermeyer forgot

We will cover the GUI part in an other issue.

**Comment by almirsarajcic** [comment]
As mentioned in https://github.com/3Stones-io/omedis/issues/522, we'll work on chat later.
