### ISSUE TITLE
LogEntry Default

### ISSUE THREAD

**Issue by wintermeyer** [3Stones-io/omedis#86]
Problem: All time has to be accounted for. There for we need a default LogEntry category.

## Tasks

- [x] Add a is_default boolean attribute to log_entry_category. #173 
- [x] Write a validation that only one log_entry_category is_default per Group can be true. All others have to be false. Think about the consequences GUI wise. When that is changed the others have to change automatically. #173 
- [x] When a Group is created we have to automatically create one log_entry_category with the name "Pause" (pause) and is_default has to be true. #179(Moved to different issue)
- [x] When no category is set in the today view that default category is set. #180
