### ISSUE TITLE
Create Project Resource

### ISSUE THREAD

**Issue by wintermeyer** [3Stones-io/omedis#89]
Create a new resource `Project` with these attributes:

- `name` String (max 140 characters)
- `tenant_id` (belongs _to)
- `position` integer

## Tasks

- [x] Add validations (e.g. position needs to be unique per tenant and so does name)
- [x] Add a GUI for all CRUD
- [x] Add links where they make sense
